# compose the demo for trace context in logs

version: '2.4'

x-logging-defaults: &logging-defaults
  driver: syslog
  options:
    syslog-address: unixgram:///dev/log
    mode: non-blocking
    tag: '{{.Name}}'

services:
  node-logdemo:
    image: node-logdemo
    build:
      context: ../apm-node-todo
    environment:
      APPOPTICS_COLLECTOR: 'collector.appoptics.com'
      APPOPTICS_SERVICE_KEY: ${APPOPTICS_API_TOKEN:?}:node-logdemo
      TODO_MONGODB_ADDRESS: 'mongodb'
      TODO_SERVER_OPTIONS: '-w 0.0.0.0:8088 -l winston:json -L all'
    logging:
      << : *logging-defaults
    ports:
      - '8001:8088'
    volumes:
      - ./node/config.js:/apm-node-todo/appoptics-apm.js
    depends_on:
      - mongodb

  mongodb:
    image: mongo

  php-logdemo:
    image: php-logdemo
    build:
      context: ./php
    environment:
      APPOPTICS_SERVICE_KEY: ${APPOPTICS_API_TOKEN:?}:php-logdemo
    logging:
      << : *logging-defaults
    ports:
      - '8002:80'
    volumes:
      - ./php/config.ini://usr/local/etc/php/conf.d/appoptics.ini
      - ./php/:/var/www/html/
