# compose the demo for trace context in logs

version: '2.4'

x-logging-defaults: &logging-defaults
  options:
    mode: non-blocking

services:
  python-logdemo:
    image: python-logdemo
    build:
      context: ./python
    environment:
      APPOPTICS_COLLECTOR: 'collector.appoptics.com'
      APPOPTICS_SERVICE_KEY: ${APPOPTICS_API_TOKEN:?}:python-logdemo
      APPOPTICS_LOG_TRACE_ID: traced
    logging:
      << : *logging-defaults
    ports:
      - '8001:8088'
    command: ["flask", "run", "-h", "0.0.0.0", "-p", "8088"]

  php-logdemo:
    image: php-logdemo
    build:
      context: ./php
    environment:
      APPOPTICS_SERVICE_KEY: ${APPOPTICS_API_TOKEN:?}:php-logdemo
    logging:
      << : *logging-defaults
    ports:
      - '8002:80'
    volumes:
      - ./php/config.ini://usr/local/etc/php/conf.d/appoptics.ini
      - ./php/:/var/www/html/
